{% set name = "libsharp" %}
{% set version = "1.0.0" %}

{% set build = 1005 %}

{% set mpi = mpi or 'nompi' %}

{% if mpi == 'nompi' %}
{% set mpi_prefix = "nompi" %}
{% else %}
{% set mpi_prefix = "mpi_" + mpi %}
{% endif %}

# Prioritize non-MPI version with the build number
{% if mpi == 'nompi' %}
{% set build = build + 100 %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Libsharp/libsharp/archive/v{{ version }}.tar.gz
  sha256: ca7cc7790c98bd5637a8a3d84460c02a54e5132b3184e713e596cd70c3cd59c0
  patches:
    - configure.ac.patch
    - setup.py.patch

build:
  number: {{ build }}
  string: "{{ mpi_prefix }}_py{{ py }}h{{ PKG_HASH }}_{{ build }}"
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf
  host:
    - llvm-openmp >=4.0.1  # [osx]
    - {{ mpi }}  # [mpi != 'nompi']
    - python
    - pip
    - setuptools
    - cython
    - numpy
  run:
    - llvm-openmp >=4.0.1  # [osx]
    - {{ mpi }}  # [mpi != 'nompi']
    - python
    - numpy

test:
  commands:
    - exit $(test -f ${PREFIX}/lib/libsharp.a)

about:
  home: https://github.com/Libsharp/libsharp.git
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: Library for fast spherical harmonic transforms, see http://arxiv.org/abs/1303.4945

extra:
  recipe-maintainers:
    - beckermr
    - tskisner
